// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfqW2U6qU2fnL3yXUR78v-I1JSueXhro',
    appId: '1:957671795678:web:569b25b15d5cb64d570b4f',
    messagingSenderId: '957671795678',
    projectId: 'tactile-pulsar-451123-q6',
    authDomain: 'tactile-pulsar-451123-q6.firebaseapp.com',
    storageBucket: 'tactile-pulsar-451123-q6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUIpR5KqQ7Q7IdjrXfqtUcdEzBeuZwOwQ',
    appId: '1:957671795678:android:bc3403183ed3d1e7570b4f',
    messagingSenderId: '957671795678',
    projectId: 'tactile-pulsar-451123-q6',
    storageBucket: 'tactile-pulsar-451123-q6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAbum7nYznSEbwiR0jry_Us2c4bYCCQ1I',
    appId: '1:957671795678:ios:a2094eed38f4eaa9570b4f',
    messagingSenderId: '957671795678',
    projectId: 'tactile-pulsar-451123-q6',
    storageBucket: 'tactile-pulsar-451123-q6.firebasestorage.app',
    iosBundleId: 'com.example.ourcommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAbum7nYznSEbwiR0jry_Us2c4bYCCQ1I',
    appId: '1:957671795678:ios:a2094eed38f4eaa9570b4f',
    messagingSenderId: '957671795678',
    projectId: 'tactile-pulsar-451123-q6',
    storageBucket: 'tactile-pulsar-451123-q6.firebasestorage.app',
    iosBundleId: 'com.example.ourcommunity',
  );
}
